@startuml EqPlatformIntegration
EqPlatform->EqPlatform : turn on
EqPlatform->Telescope: {runtimeFromCenter:343.44,currentlyRunning:1}
AlpacaClient->Telescope : http://...80 /api/v1/telecscope/rightascension
Telescope->Telescope: getRA()
Telescope->Telescope: updatePosition()
Telescope->Telescope: setEncoderValues()
Telescope->Telescope: calculateCurrentPosition
EqPlatform->AlpacaClient: current RA


      
